services:
# web_server の立ち上げ
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    container_name: web_server

  database:
    image: postgres:latest
    environment:
      POSTGRES_ROOT_PASSWORD: rootpassword
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budget_db
    ports:
      - "5432:5432"
    volumes: # postgresのデータを/var/lib/postgresql/dataにマウントし永続化
      - postgres_data:/var/lib/postgresql
    container_name: database

# サービスで使用する volume を定義
volumes:
  postgres_data:
    driver: local